"""initial_schema

Revision ID: 444784d636fa
Revises: 0001_initial_schema
Create Date: 2026-05-22 10:02:45.470964
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '444784d636fa'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('discount_type', sa.Enum('percent', 'flat', name='coupon_discount_type'), nullable=False),
    sa.Column('discount_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_discount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('min_booking_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('applicable_for', sa.Enum('all', 'new_users', 'specific_users', name='coupon_applicable_for'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.Enum('manual', 'automatic', name='car_transmission'), nullable=False),
    sa.Column('fuel_type', sa.Enum('petrol', 'diesel', 'electric', 'hybrid', 'cng', name='car_fuel_type'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('hatchback', 'sedan', 'suv', 'muv', 'luxury', 'electric', 'convertible', 'minivan', name='car_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('location_city', sa.String(length=100), nullable=False),
    sa.Column('location_area', sa.String(length=200), nullable=True),
    sa.Column('location_lat', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_lng', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('price_per_hour', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('price_per_day', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('min_trip_hours', sa.Integer(), nullable=False),
    sa.Column('max_trip_days', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('extra_km_charge', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('included_km_per_day', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('has_gps_tracker', sa.Boolean(), nullable=False),
    sa.Column('has_keyless_entry', sa.Boolean(), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('has_music_system', sa.Boolean(), nullable=False),
    sa.Column('has_sunroof', sa.Boolean(), nullable=False),
    sa.Column('has_child_seat', sa.Boolean(), nullable=False),
    sa.Column('has_luggage_carrier', sa.Boolean(), nullable=False),
    sa.Column('minimum_guest_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('auto_accept_bookings', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_host_id'), 'cars', ['host_id'], unique=False)
    op.create_index(op.f('ix_cars_location_city'), 'cars', ['location_city'], unique=False)
    op.create_index(op.f('ix_cars_registration_number'), 'cars', ['registration_number'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.create_table('host_payout_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'paid', 'failed', name='host_payout_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('response_time', sa.String(length=100), nullable=True),
    sa.Column('acceptance_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('total_listings', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('is_superhost', sa.Boolean(), nullable=False),
    sa.Column('joined_as_host_at', sa.DateTime(), nullable=False),
    sa.Column('payout_bank_name', sa.String(length=200), nullable=True),
    sa.Column('payout_account_number', sa.String(length=50), nullable=True),
    sa.Column('payout_ifsc', sa.String(length=20), nullable=True),
    sa.Column('payout_account_holder', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token'), 'password_resets', ['token'], unique=True)
    op.create_table('support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_ref', sa.String(length=12), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('booking', 'payment', 'car_issue', 'account', 'other', name='support_ticket_category'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='support_ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='support_ticket_priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_kyc',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dl_number', sa.String(length=50), nullable=True),
    sa.Column('dl_front_image', sa.String(length=500), nullable=True),
    sa.Column('dl_back_image', sa.String(length=500), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('aadhar_front_image', sa.String(length=500), nullable=True),
    sa.Column('aadhar_back_image', sa.String(length=500), nullable=True),
    sa.Column('kyc_status', sa.Enum('pending', 'under_review', 'approved', 'rejected', name='kyc_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_wallet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.Enum('credit', 'debit', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_ref', sa.String(length=12), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('guest_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'active', 'completed', 'cancelled', 'rejected', name='booking_status'), nullable=False),
    sa.Column('pickup_datetime', sa.DateTime(), nullable=False),
    sa.Column('return_datetime', sa.DateTime(), nullable=False),
    sa.Column('actual_pickup_time', sa.DateTime(), nullable=True),
    sa.Column('actual_return_time', sa.DateTime(), nullable=True),
    sa.Column('pickup_location', sa.Text(), nullable=True),
    sa.Column('total_hours', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('base_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('insurance_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('insurance_plan', sa.Enum('basic', 'standard', 'platinum', name='insurance_plan'), nullable=True),
    sa.Column('security_deposit_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('host_earnings', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('extra_km_charged', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('odometer_start', sa.Integer(), nullable=True),
    sa.Column('odometer_end', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=36), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('refund_status', sa.Enum('not_applicable', 'pending', 'processed', name='refund_status'), nullable=False),
    sa.Column('host_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('guest_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_ref'), 'bookings', ['booking_ref'], unique=True)
    op.create_table('car_availability_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_from', sa.DateTime(), nullable=False),
    sa.Column('blocked_to', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_images_car_id'), 'car_images', ['car_id'], unique=False)
    op.create_table('car_pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('car_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.Enum('weekend_discount', 'long_trip_discount', 'peak_surcharge', name='car_pricing_rule_type'), nullable=False),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('surcharge_percent', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('min_days', sa.Integer(), nullable=True),
    sa.Column('applies_on', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_extensions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('extended_return_datetime', sa.DateTime(), nullable=False),
    sa.Column('additional_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='booking_extension_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('payment_method', sa.Enum('simulated', 'wallet', 'upi', 'card', name='payment_method'), nullable=False),
    sa.Column('simulated_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('guest', 'host', 'admin', name='user_role'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('guest', 'host', 'admin', name='user_role'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.drop_table('payments')
    op.drop_table('coupon_usages')
    op.drop_table('booking_extensions')
    op.drop_table('car_pricing_rules')
    op.drop_index(op.f('ix_car_images_car_id'), table_name='car_images')
    op.drop_table('car_images')
    op.drop_table('car_availability_blocks')
    op.drop_index(op.f('ix_bookings_booking_ref'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('wallet_transactions')
    op.drop_table('user_wallet')
    op.drop_table('user_kyc')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_password_resets_token'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_table('host_profiles')
    op.drop_table('host_payout_requests')
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_cars_registration_number'), table_name='cars')
    op.drop_index(op.f('ix_cars_location_city'), table_name='cars')
    op.drop_index(op.f('ix_cars_host_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
